Add tests for registration
scriptkitties/ravenmail-webui pull request #8
Opened 2017-02-28 07:10 UTC by Tyil

2017-02-28 07:28 UTC, KingNoosh reviewed
The only thing I can just see is that the unit tests might not be strong enough. However, I don't know whether this might be enough group to request changes, so I'm leaving them up to you as suggestions.

2017-02-28 07:28 UTC, KingNoosh commented on tests/RegistrationTest.php
> +        $this->assertRedirectedToRoute('user.create', [], [],
Would it not be a good idea to check what the exception here is too alongside the redirect?

2017-02-28 07:28 UTC, KingNoosh commented on tests/RegistrationTest.php
> +        $this->assertRedirectedToRoute('user.create', [], [],
Would it not be a good idea to check what the exception here is too alongside the redirect?

2017-02-28 07:28 UTC, KingNoosh commented on tests/RegistrationTest.php
> +        $this->assertRedirectedToRoute('user.create', [], [],
Would it not be a good idea to check what the exception here is too alongside the redirect?

2017-02-28 07:32 UTC, KingNoosh approved these changes
Forgot to click approve. :^)

2017-02-28 07:41 UTC, Tyil commented on tests/RegistrationTest.php
> +        $this->assertRedirectedToRoute('user.create', [], [],
That would probably be good, yeah. I'm only checking the bare technical basics here, I'll read up on the Laravel docs to see if I can check for the specific errors given in a request. If anyone else knows about this already, do inform me.

2017-03-01 09:40 UTC, KingNoosh requested changes
Prepping for re-review as the Laravel update has had some breaking changes. Reply to this comment once it's at a stage where it needs reviewing. :)

2017-03-01 11:25 UTC, Tyil commented
@KingNoosh: that was a failing seedscript :(

2017-03-02 18:24 UTC, KingNoosh approved these changes
Looks fine to me

2017-03-05 22:04 UTC, merged